---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: entitlements-api-go
  namespace: hcc-accessmanagement-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: entitlements-api-go
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: entitlements-api-go
  namespace: hcc-accessmanagement-tenant
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    # If building an FBC component, replace the above line with the one below
    # build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
spec:
  application: entitlements-api-go
  componentName: entitlements-api-go
  source:
    git:
      revision: main
      url: https://github.com/RedHatInsights/entitlements-api-go/tree/main
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: imagerepository-for-entitlements-api-go-entitlements-api-go
  namespace: hcc-accessmanagement-tenant
  labels:
    appstudio.redhat.com/application: entitlements-api-go
    appstudio.redhat.com/component: entitlements-api-go
spec:
  image:
    name: hcc-accessmanagement-tenant/entitlements-api-go/entitlements-api-go
    visibility: public