apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#platform-feedback
- integration_test_scenario.yaml
- release_plan.yaml 

#entitlements-api-go 
- entitlements-api-go.yaml
- entitlements_api_go_integration_test.yaml

#uhc-auth-proxy 
- uhc-auth-proxy.yaml 
- uhc_auth_proxy_integration_test.yaml

namespace: hcc-accessmanagement-tenant