apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: platform-feedback-release-as-ms
  namespace: hcc-accessmanagement-tenant
spec:
  application: platform-feedback
  target: rhtap-releng-tenant
