apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: entitlements-api-go
    appstudio.redhat.com/component: entitlements-api-go
  name: imagerepository-for-entitlements-api-go-entitlements-api-go
  namespace: hcc-accessmanagement-tenant
spec:
  image:
    name: hcc-accessmanagement-tenant/entitlements-api-go/entitlements-api-go
    visibility: public
