apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac
  name: uhc-auth-proxy
  namespace: hcc-accessmanagement-tenant
spec:
  application: uhc-auth-proxy
  componentName: uhc-auth-proxy
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/RedHatInsights/uhc-auth-proxy/tree/master
