apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  annotations:
    hello: world
  name: entitlements-api-go
  namespace: hcc-accessmanagement-tenant
spec:
  displayName: entitlements-api-go
