apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: uhc-auth-proxy
    appstudio.redhat.com/component: uhc-auth-proxy
  name: imagerepository-for-uhc-auth-proxy-uhc-auth-proxy
  namespace: hcc-accessmanagement-tenant
spec:
  image:
    name: hcc-accessmanagement-tenant/uhc-auth-proxy/uhc-auth-proxy
    visibility: public
